# Generated by Django 3.0.2 on 2020-02-01 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GameModel',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('current_player', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='PlayerModel',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('chips', models.IntegerField()),
            ],
        ),
    ]
