# Generated by Django 3.0.2 on 2020-02-08 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poker_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='all_played',
        ),
        migrations.RemoveField(
            model_name='game',
            name='game_over',
        ),
        migrations.RemoveField(
            model_name='game',
            name='last_raise',
        ),
        migrations.RemoveField(
            model_name='game',
            name='round_ended',
        ),
    ]
