# Generated by Django 3.0.2 on 2020-02-08 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poker_app', '0003_auto_20200208_1625'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
