# docker-compose --file docker-compose-dev.yaml up

# docker exec --tty --interactive jjnt-django python manage.py createsuperuser
# docker exec poker python manage.py makemigrations
# docker exec poker python manage.py migrate
# docker exec poker python manage.py clean-db


version: '3'

services:
    redis:
        container_name: poker-redis
        image: redis:latest
        # command: redis-server --requirepass redispass
        command: redis-server
        ports:
            - 6379:6379
    django:
        build:
            context: ./
            dockerfile: Django.Dockerfile
        image: poker-django
        container_name: poker-django
        volumes:
            - ./:/poker/
        ports:
            - 8000:8000
        depends_on:
          - redis
    react:
        build:
            context: ./
            dockerfile: React.Dockerfile
        image: poker-react
        container_name: poker-react
        volumes:
            - ./:/poker/
        ports:
            - 3000:3000
        depends_on:
            - django