# Generated by Django 3.0.5 on 2020-05-08 14:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_player', models.IntegerField(default=0)),
                ('last_raise', models.IntegerField(default=0)),
                ('biggest_bid', models.IntegerField(default=0)),
                ('all_played', models.BooleanField(default=False)),
                ('game_over', models.BooleanField(default=False)),
                ('round_ended', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chips', models.IntegerField(default=0)),
                ('highest_combination', models.IntegerField(default=0)),
                ('pot', models.IntegerField(default=0)),
                ('round_bid', models.IntegerField(default=0)),
                ('can_check', models.BooleanField(default=False)),
                ('can_raise', models.BooleanField(default=False)),
                ('can_call', models.BooleanField(default=False)),
                ('is_folded', models.BooleanField(default=False)),
                ('is_all_in', models.BooleanField(default=False)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Game')),
            ],
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('suit', models.CharField(max_length=10)),
                ('rank', models.CharField(max_length=2)),
                ('location', models.CharField(default='DECK', max_length=6)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Game')),
                ('player', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Player')),
            ],
        ),
    ]
