# Generated by Django 3.0.2 on 2020-02-15 17:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('can_check', models.BooleanField(default=False)),
                ('can_raise', models.BooleanField(default=False)),
                ('can_call', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='BurnedCards',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('suit', models.CharField(max_length=10)),
                ('rank', models.CharField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Deck',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='api.Card')),
            ],
        ),
        migrations.CreateModel(
            name='Hand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='api.Card')),
            ],
        ),
        migrations.CreateModel(
            name='TableCards',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='api.Card')),
            ],
        ),
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('burned', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='api.BurnedCards')),
                ('cards', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='api.TableCards')),
                ('deck', models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, to='api.Deck')),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chips', models.IntegerField()),
                ('highest_combination', models.IntegerField(default=10)),
                ('pot', models.IntegerField(default=0)),
                ('round_bid', models.IntegerField(default=0)),
                ('is_folded', models.BooleanField(default=False)),
                ('is_all_in', models.BooleanField(default=False)),
                ('actions', models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, to='api.Action')),
                ('hand', models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, to='api.Hand')),
                ('owner', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='players', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_player', models.IntegerField(default=0)),
                ('last_raise', models.IntegerField(default=0)),
                ('biggest_bid', models.IntegerField(default=0)),
                ('all_played', models.BooleanField(default=False)),
                ('game_over', models.BooleanField(default=False)),
                ('round_ended', models.BooleanField(default=False)),
                ('players', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='api.Player')),
                ('table', models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, to='api.Table')),
            ],
        ),
        migrations.AddField(
            model_name='burnedcards',
            name='card',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='api.Card'),
        ),
    ]
