# Generated by Django 3.0.5 on 2020-04-10 23:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='players',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.Player'),
        ),
        migrations.AlterField(
            model_name='game',
            name='table',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.Table'),
        ),
    ]
