# Generated by Django 3.0.7 on 2020-07-20 12:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_players', models.IntegerField(default=8)),
                ('players_connected', models.IntegerField(default=0)),
                ('dealer', models.IntegerField(default=0)),
                ('current_player', models.IntegerField(default=0)),
                ('big_blind_player', models.IntegerField(default=0)),
                ('small_blind_player', models.IntegerField(default=0)),
                ('starting_chips', models.IntegerField(default=200)),
                ('small_blind', models.IntegerField(default=5)),
                ('big_blind', models.IntegerField(default=10)),
                ('last_raise', models.IntegerField(default=0)),
                ('biggest_bet', models.IntegerField(default=0)),
                ('rounds_played', models.IntegerField(default=0)),
                ('all_played', models.BooleanField(default=False)),
                ('game_over', models.BooleanField(default=False)),
                ('round_ended', models.BooleanField(default=False)),
                ('game_initialized', models.BooleanField(default=False)),
                ('path', models.CharField(max_length=30)),
                ('name', models.SlugField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_action', models.CharField(blank=True, max_length=20)),
                ('last_raise', models.IntegerField(default=0)),
                ('in_game_order', models.IntegerField(default=0)),
                ('chips', models.IntegerField(default=0)),
                ('highest_combination', models.IntegerField(default=0)),
                ('pot', models.IntegerField(default=0)),
                ('round_bet', models.IntegerField(default=0)),
                ('is_in_game', models.BooleanField(default=False)),
                ('can_check', models.BooleanField(default=False)),
                ('can_raise', models.BooleanField(default=False)),
                ('can_call', models.BooleanField(default=False)),
                ('is_folded', models.BooleanField(default=False)),
                ('is_all_in', models.BooleanField(default=False)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.Game')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.User')),
            ],
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('suit', models.CharField(max_length=10)),
                ('rank', models.CharField(max_length=2)),
                ('value', models.IntegerField()),
                ('image', models.CharField(max_length=20)),
                ('location', models.CharField(default='DECK', max_length=6)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.Game')),
                ('player', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='game.Player')),
            ],
        ),
    ]
