# Generated by Django 3.0.7 on 2020-07-17 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='last_action',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
